z

diff --git a/.github/workflows/pr_tests.yml b/.github/workflows/pr_tests.yml
--- a/.github/workflows/pr_tests.yml
+++ b/.github/workflows/pr_tests.yml
@@ -139,34 +139,6 @@ jobs:
 ####          GITHUB_CONTEXT: ${{ toJson(github) }}
 ####        run: echo "$GITHUB_CONTEXT"
 ###
-  examine_contexts:
-    name: 'Examine Context contents'
-    if: always()
-    env:
-      THING: ${{ github.event.repository.name }}
-      ORG: ${{ github.event.organization.login }}
-    runs-on: ubuntu-latest
-      ###needs: [ glci-syntax, contributor-permissions ]
-    steps:
-      - name: Dump context1
-        env:
-          VARS_CONTEXT: ${{ toJson(vars) }}
-        run: echo "$VARS_CONTEXT"
-      - name: Dump context2
-        env:
-          VARS2_CONTEXT: ${{ toJson(secrets) }}
-        run: echo "$VARS2_CONTEXT"
-      - name: Dump env vars
-        run: env | sort
-      - name: validate secrets and vars
-        env:
-          _API: ${{ vars.GITLAB_API_URL }}
-          _TOK: ${{ secrets.GITLAB_API_PRIVATE_TOKEN }}
-        run: |
-          [[ -z $_API ]] && echo '::error ::vars.GITLAB_API_URL is empty!'
-          [[ -z $_TOK ]] && echo '::error ::secrets.GITLAB_API_PRIVATE_TOKEN is empty!'
-          echo
-
 
   # The ONLY reason we can validate the PR HEAD's content safely here is that
   # we restrict ourselves to sending data elsewhere.
@@ -177,11 +149,18 @@ jobs:
       valid: ${{ steps.validate-glci-file.outputs.valid }}
     steps:
       - uses: actions/checkout@v3
+      - name: Validate required secrets and vars
+        env:
+          _API: ${{ vars.GITLAB_API_URL }}
+          _TOK: ${{ secrets.GITLAB_API_PRIVATE_TOKEN }}
+        run: |
+          [[ -n $_API ]] || echo '::error ::vars.GITLAB_API_URL is empty!'
+          [[ -n $_TOK ]] || echo '::error ::secrets.GITLAB_API_PRIVATE_TOKEN is empty!'
+          [[ -n $_API ]] && [[ -n $_TOK ]]
       - name: 'Validate GLCI file syntax'
         id: validate-glci-file
         uses: simp/github-action-gitlab-ci-syntax-check@tests/fix-gitlab-api
         with:
           gitlab_api_private_token: ${{ secrets.GITLAB_API_PRIVATE_TOKEN }}
           gitlab_api_url: ${{ vars.GITLAB_API_URL }}
-            #gitlab_api_url: https://gitlab.sicura.dev/api/v4/projects/694
 
